site_name: Gitomail
site_description: Gitomail
site_author: Dan Aloni
repo_url: https://github.com/kernelim/gitomail/tree/master/doc
copyright: Copyright (c) 2015-2016, Dan Aloni
docs_dir: doc
site_dir: _site
theme: readthedocs

pages:
- Home: index.md
- Changelog: ChangeLog.md
- Documentation:
  - Installation: install.md
  - Execution: execution.md
  - Configuration: config.md
  - Recommended GMail filters: gmail.md

markdown_extensions:
- toc:
    permalink: true
