flags: {}
packages:
- location: https://github.com/kernelim/leveldb-haskell/archive/6e92a6cb26b6f75857e95705c15902b85758dd53.zip
  extra-dep: true
- location: https://github.com/da-x/fancydiff/archive/4052768d5538c052a86e98a7f029f298254d4c73.zip
  extra-dep: true
- location: https://github.com/da-x/gitlib/archive/5b1ad46aaf091802b26828c68c625dac5a0e7444.zip
  extra-dep: true
  subdirs:
  - gitlib
  - gitlib-libgit2
  - hlibgit2
- .
resolver: lts-7.15
