flags: {}
packages:
- location: https://github.com/kernelim/leveldb-haskell/archive/6e92a6cb26b6f75857e95705c15902b85758dd53.zip
  extra-dep: true
- location: https://github.com/da-x/fancydiff/archive/b9cd7a24f151c91d1dd64690d0d1c9de1928d43a.zip
  extra-dep: true
- location: https://github.com/da-x/gitlib/archive/5b338169a2618337a60aaf17e2ab56a2654b1244.zip
  extra-dep: true
  subdirs:
  - gitlib
  - gitlib-libgit2
  - hlibgit2
- .
resolver: lts-5.4
