flags: {}
packages:
- location: https://github.com/kernelim/leveldb-haskell/archive/6e92a6cb26b6f75857e95705c15902b85758dd53.zip
  extra-dep: true
- location: https://github.com/da-x/fancydiff/archive/7150464256ee05500f8bb8e0a08773583c20875b.zip
  extra-dep: true
- location: https://github.com/da-x/gitlib/archive/5b338169a2618337a60aaf17e2ab56a2654b1244.zip
  extra-dep: true
  subdirs:
  - gitlib
  - gitlib-libgit2
  - hlibgit2
- .
resolver: lts-5.4
